"""empty message

Revision ID: 169ae8b996a2
Revises: 6d5f7d8b6753
Create Date: 2022-08-19 09:47:26.124156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169ae8b996a2'
down_revision = '6d5f7d8b6753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resilience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('treatment_scale_by_other', sa.Integer(), nullable=False),
    sa.Column('engaged_socially_today', sa.Boolean(create_constraint=256), nullable=False),
    sa.Column('engagement_activities', sa.String(length=256), nullable=True),
    sa.Column('type_of_feelings', sa.String(length=256), nullable=False),
    sa.Column('feelings_experienced', sa.String(length=256), nullable=True),
    sa.Column('reason_for_feelings', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resilience')
    # ### end Alembic commands ###
