"""empty message

Revision ID: 1b2c540db76a
Revises: 3bb24cccaa20
Create Date: 2022-11-01 13:17:38.789639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b2c540db76a'
down_revision = '3bb24cccaa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profileImage', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user', 'profileImage')
    # ### end Alembic commands ###
