"""empty message

Revision ID: 3bb24cccaa20
Revises: 5e19435129ca
Create Date: 2022-11-01 12:59:36.727425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb24cccaa20'
down_revision = '5e19435129ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.LargeBinary(), nullable=True))
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'age_of_onset',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'caregiver_contact',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'caregiver_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'institution',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'seizure_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'seizure_type',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'institution',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'caregiver_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'caregiver_contact',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'age_of_onset',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###
