"""empty message

Revision ID: 5e19435129ca
Revises: dd6d6fb8a8ad
Create Date: 2022-10-28 09:43:49.933143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e19435129ca'
down_revision = 'dd6d6fb8a8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('age_of_onset', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('caregiver_contact', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('caregiver_name', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('institution', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('seizure_type', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seizure_type')
    op.drop_column('user', 'institution')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'caregiver_name')
    op.drop_column('user', 'caregiver_contact')
    op.drop_column('user', 'age_of_onset')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
