"""empty message

Revision ID: 8f8aa4c79087
Revises: a0382745d837
Create Date: 2022-09-30 06:23:37.255488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f8aa4c79087'
down_revision = 'a0382745d837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('engaged_socially_today', sa.Boolean(create_constraint=256), nullable=False),
    sa.Column('engagement_activities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('treatment_scale_by_other', sa.Integer(), nullable=False),
    sa.Column('type_of_feelings', sa.String(length=256), nullable=False),
    sa.Column('feelings_experienced', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_for_feelings', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medication', sa.Column('reason_missed_dose', sa.String(length=255), nullable=True))
    op.drop_column('medication', 'experienced_side_effects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('experienced_side_effects', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('medication', 'reason_missed_dose')
    op.drop_table('feeling')
    op.drop_table('activity')
    # ### end Alembic commands ###
