"""empty message

Revision ID: b90ea4414e5b
Revises: 1b2c540db76a
Create Date: 2022-11-07 14:43:19.950053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b90ea4414e5b'
down_revision = '1b2c540db76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profileImage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profileImage', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
