"""empty message

Revision ID: dd6d6fb8a8ad
Revises: 8f8aa4c79087
Create Date: 2022-10-21 19:54:14.293575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6d6fb8a8ad'
down_revision = '8f8aa4c79087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('experienced_side_effects', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication', 'experienced_side_effects')
    # ### end Alembic commands ###
