"""empty message

Revision ID: e00d934e827b
Revises: c288f3e3ad63
Create Date: 2022-06-24 00:23:17.743374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00d934e827b'
down_revision = 'c288f3e3ad63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seizure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seizure_severity', sa.String(length=256), nullable=False),
    sa.Column('seizure_duration', sa.String(length=256), nullable=False),
    sa.Column('seizure_time_of_day', sa.String(length=256), nullable=False),
    sa.Column('lost_awareness', sa.Boolean(create_constraint=256), nullable=False),
    sa.Column('experienced_aura', sa.Boolean(), nullable=False),
    sa.Column('aura_location', sa.String(length=256), nullable=True),
    sa.Column('aura_kind_experienced', sa.String(length=256), nullable=True),
    sa.Column('was_seizure_triggered', sa.Boolean(), nullable=False),
    sa.Column('seizure_trigger', sa.String(length=256), nullable=True),
    sa.Column('seizure_impact', sa.String(length=256), nullable=False),
    sa.Column('seizure_impact_upset_you', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seizure')
    # ### end Alembic commands ###
