"""empty message

Revision ID: e5cf426cbc4d
Revises: efda4abc15cb
Create Date: 2022-11-10 00:20:15.929943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cf426cbc4d'
down_revision = 'efda4abc15cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('medication', 'experienced_side_effects',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.execute('''UPDATE "medication" SET experienced_side_effects = false; ''')
    op.alter_column('medication', 'experienced_side_effects',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medication', 'experienced_side_effects',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('user_role')
    op.drop_table('role')
    # ### end Alembic commands ###
