"""empty message

Revision ID: efda4abc15cb
Revises: b90ea4414e5b
Create Date: 2022-11-07 14:43:45.024795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efda4abc15cb'
down_revision = 'b90ea4414e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profileImage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profileImage')
    # ### end Alembic commands ###
